myphotos/myphotos/main/default/objects/Place__c/Place__c.object-meta.xml
<CustomObject>
    <label>Place</label>
    <nameField>
        <label>Place Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdc/myphotos/main/default/objects/Place__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

sfdc/myphotos/main/default/objects/Place__c/fields/Geolocation__c.field-meta.xml
<CustomField>
    <fullName>Geolocation__c</fullName>
    <label>Geolocation</label>
    <required>true</required>
    <scale>8</scale>
    <type>Location</type>
</CustomField>

sfdc/myphotos/main/default/objects/Record__c/Record__c.object-meta.xml
<CustomObject>
    <description>Records for My Photos app</description>
    <label>Record</label>
    <nameField>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdc/myphotos/main/default/objects/Record__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <description>Address</description>
    <inlineHelpText>Address</inlineHelpText>
    <label>Address</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

sfdc/myphotos/main/default/objects/Record__c/fields/Distance__c.field-meta.xml
<CustomField>
    <fullName>Distance__c</fullName>
    <formula>Round(Distance(Geolocation__c, $User.Geolocation__c, &apos;km&apos;),2)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Distance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfdc/myphotos/main/default/objects/Record__c/fields/Geolocation__c.field-meta.xml
<CustomField>
    <fullName>Geolocation__c</fullName>
    <description>Latitude and longitude</description>
    <inlineHelpText>Latitude and longitude</inlineHelpText>
    <label>Geolocation</label>
    <scale>8</scale>
    <type>Location</type>
</CustomField>

sfdc/myphotos/main/default/objects/Record__c/fields/Place__c.field-meta.xml
<CustomField>
    <fullName>Place__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Place</label>
    <referenceTo>Place__c</referenceTo>
    <relationshipLabel>Record</relationshipLabel>
    <relationshipName>Records</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdc/myphotos/main/default/classes/PlaceObject.cls
global with sharing class PlaceObject {

    global static Decimal VICINITY_RADIUS = 0.1;  // 100m

    @AuraEnabled
    global static Boolean addPlace(Id recordId) {
        Boolean success = false;
        try {
            Record__c r = [
                SELECT Name, Address__c, Geolocation__Latitude__s, Geolocation__Longitude__s, Place__c
                FROM Record__c
                WHERE Id = :recordId
                LIMIT 1
            ];
            
            Decimal latitude = r.Geolocation__Latitude__s;
            Decimal longitude = r.Geolocation__Longitude__s;

            List<Place__c> places = [
                SELECT Name, Address__c, Geolocation__Latitude__s, Geolocation__Longitude__s
                FROM Place__c
                WHERE DISTANCE(Geolocation__c, GEOLOCATION(:latitude, :longitude), 'km')  < :VICINITY_RADIUS
            ];
            if (places.size() == 0) {
                Place__c place = new Place__c();
                place.Name = r.Name;
                place.Address__c = r.Address__c;
                place.Geolocation__Latitude__s = latitude;
                place.Geolocation__Longitude__s = longitude;
                insert place;

                r.Place__c = place.Id;
                update r;

                success = true;
                System.debug(place);
            } else {
                r.Place__c = places[0].Id;
                update r;
            }
            return success;
   
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled(cacheable=true)
    global static String findPlace(){
        String name = '';
        try {
            List<Place__c> place = [
                SELECT Name
                FROM Place__c
                WHERE Distance__c < :VICINITY_RADIUS
                LIMIT 1
            ];
            System.debug(place);
            if (place.size() != 0) {
                name = place[0].Name;
            }
            return name;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}