myphotos/myphotos/main/default/objects/Place__c/Place__c.object-meta.xml
<CustomObject>
    <label>Place</label>
    <nameField>
        <label>Place Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdc/myphotos/main/default/objects/Record__c/Record__c.object-meta.xml
<CustomObject>
    <description>Records for My Photos app</description>
    <label>Record</label>
    <nameField>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

myphotos/myphotos/main/default/objects/Record__c/fields/Memo__c.field-meta.xml
<CustomField>
    <fullName>Memo__c</fullName>
    <description>Memo</description>
    <inlineHelpText>Memo</inlineHelpText>
    <label>Memo</label>
    <type>TextArea</type>
</CustomField>

sfdc/myphotos/main/default/objects/Record__c/fields/Place__c.field-meta.xml
<CustomField>
    <fullName>Place__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Place</label>
    <referenceTo>Place__c</referenceTo>
    <relationshipLabel>Record</relationshipLabel>
    <relationshipName>Records</relationshipName>
    <type>Lookup</type>
</CustomField>

myphotos/myphotos/main/default/objects/Record__c/recordTypes/Public.recordType-meta.xml
<RecordType>
    <fullName>Public</fullName>
    <active>true</active>
    <description>Open to the public</description>
    <label>Public</label>
</RecordType>

sfdc/myphotos/main/default/classes/PlaceCheckTest.cls
@isTest
public with sharing class PlaceCheckTest {

    @isTest
    static void isAlreadyRegisteredTest() {
        Place__c place = new Place__c(
            Name='Apita Yokohama Tsunashima test place 123',
            Geolocation__Latitude__s=35.54258299,
            Geolocation__Longitude__s=139.64165449
        );
        insert place;

        Record__c record = new Record__c(
            Name='Apita Yokohama Tsunashima test place 345',
            Memo__c='Remote working now',
            Geolocation__Latitude__s=35.54258299219887,
            Geolocation__Longitude__s=139.64165440712304
        );
        insert record;

        record = [SELECT Id FROM Record__c WHERE Name = 'Apita Yokohama Tsunashima test place 345'];
        
        Boolean isAlreadyRegistered = PlaceCheck.isAlreadyRegistered(record.Id);
        System.assertEquals(true, isAlreadyRegistered);        
    }
}