myphotos/myphotos/main/default/objects/Record__c/Record__c.object-meta.xml
<CustomObject>
    <description>Records for My Photos app</description>
    <label>Record</label>
    <nameField>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdc/myphotos/main/default/objects/Record__c/fields/Geolocation__c.field-meta.xml
<CustomField>
    <fullName>Geolocation__c</fullName>
    <description>Latitude and longitude</description>
    <inlineHelpText>Latitude and longitude</inlineHelpText>
    <label>Geolocation</label>
    <scale>8</scale>
    <type>Location</type>
</CustomField>

myphotos/myphotos/main/default/objects/Record__c/fields/Memo__c.field-meta.xml
<CustomField>
    <fullName>Memo__c</fullName>
    <description>Memo</description>
    <inlineHelpText>Memo</inlineHelpText>
    <label>Memo</label>
    <type>TextArea</type>
</CustomField>

sfdc/myphotos/main/default/objects/Record__c/fields/Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Timestamp__c</fullName>
    <description>Timestamp</description>
    <inlineHelpText>Timestamp</inlineHelpText>
    <label>Timestamp</label>
    <type>DateTime</type>
</CustomField>

myphotos/myphotos/main/default/objects/Record__c/fields/uuid__c.field-meta.xml
<CustomField>
    <fullName>uuid__c</fullName>
    <description>UUID</description>
    <externalId>true</externalId>
    <inlineHelpText>UUID</inlineHelpText>
    <label>UUID</label>
    <length>36</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

myphotos/myphotos/main/default/objects/Record__c/recordTypes/Public.recordType-meta.xml
<RecordType>
    <fullName>Public</fullName>
    <active>true</active>
    <description>Open to the public</description>
    <label>Public</label>
</RecordType>

myphotos/force-app/main/default/classes/SelectRecords.cls
public with sharing class SelectRecords {

    @AuraEnabled(cacheable=true)
    public static List<Record__c> selectRecordsByDistance(Decimal latitude, Decimal longitude, Decimal radius) {
        return [
            SELECT Id, uuid__c, Name, Memo__c, Timestamp__c, Geolocation__Latitude__s, Geolocation__Longitude__s
            FROM Record__c
            WHERE DISTANCE(Geolocation__c, GEOLOCATION(:latitude, :longitude), 'km') < :radius
        ];
    }
}