sfdc/myphotos/main/default/objects/Record__c/Record__c.object-meta.xml
<CustomObject>
    <description>Records for My Photos app</description>
    <label>Record</label>
    <nameField>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

myphotos/myphotos/main/default/objects/Record__c/fields/Memo__c.field-meta.xml
<CustomField>
    <fullName>Memo__c</fullName>
    <description>Memo</description>
    <inlineHelpText>Memo</inlineHelpText>
    <label>Memo</label>
    <type>TextArea</type>
</CustomField>

myphotos/myphotos/main/default/objects/Record__c/recordTypes/Public.recordType-meta.xml
<RecordType>
    <fullName>Public</fullName>
    <active>true</active>
    <description>Open to the public</description>
    <label>Public</label>
</RecordType>

sfdc/myphotos/main/default/classes/PlaceObjectTest.cls
@isTest
public with sharing class PlaceObjectTest {

    static String PLACE_NAME = 'Apita Yokohama Tsunashima test place 345';
    
    @TestSetup
    static void makeData(){
        Record__c record = new Record__c(
            Name = PLACE_NAME,
            Memo__c = 'Remote working now',
            Geolocation__Latitude__s = 35.54258299219887,
            Geolocation__Longitude__s = 139.64165440712304
        );
        insert record;
    }

    @isTest
    static void addPlaceTest() {
        Record__c record = [SELECT Id FROM Record__c WHERE Name = :PLACE_NAME];
        Boolean success = PlaceObject.addPlace(record.Id);
        System.assertEquals(true, success);

        record = [SELECT Id FROM Record__c WHERE Name = :PLACE_NAME];
        success = PlaceObject.addPlace(record.Id);
        System.assertEquals(false, success);
    }

    @isTest
    static void findPlaceTest() {

        Id userId = UserInfo.getUserId();
        Decimal latitude = 35.54258299;
        Decimal longitude = 139.64165449;
        UserObject.updateGeolocation(userId, latitude, longitude);

        Record__c record = [SELECT Id FROM Record__c WHERE Name = :PLACE_NAME];
        Boolean success = PlaceObject.addPlace(record.Id);

        String placeName = PlaceObject.findPlace();
        System.assertEquals(PLACE_NAME, placeName);
    }

}